### ISSUE TITLE
non-empty UUID with backend PUT error

### ISSUE THREAD

**Issue by gilreathjw** [prebid/prebid-cache#119] opened 2022-11-10 14:34 UTC
On line 305 in endpoints/put.go, you don't set the uuid to be empty even though there was an error performing the PUT, making the uuid itself useless since it can't actually be used to fetch from the backend. The solution is to do `resp.UUID = ""` in both branches of the if/else. I would create a pull request for this, but I don't have permission to push a branch to this repository.

**Comment by SyntaxNode** [comment] 2023-01-30 18:46
@gilreathjw According to @guscarreon, the data structure is not used for a response if there is a put error - thus, there is no need to set the UUID to empty. Have you encountered a case where a non-empty UUID is returned when it should not? If so, please share the steps to reproduce.

**Comment by gilreathjw** [comment] 2023-01-31 15:45
Hi Scott, that is exactly what I mean - this very behavior was observed in production usage. This issue was reported several months ago, and at this point I don't remember all of the specifics; that being said, based on our conversation logs in Slack the issue *might* have been caused by memcached evicting items and then a request being sent to prebid-cache to retrieve said evicted item, and when it wasn't there, having the response ultimately contain an `error` - but also a `uuid`. But as I said, I can't be sure - this was gleaned from incomplete conversation, much was said in person that is now lost.

It could also have been related to the fact that the prebid-cache library treats a connection timeout as a 'bad' connection, and anytime you try to insert with a bad connection, it closes that connection and opens a new one. This has the side-effect of making the issue worse, leading to more timeouts, which lead to more closed and new connections, which makes it even worse... ultimately leading to a 100% failure of a cluster running prebid-cache.

**Comment by bsardo** [comment] 2023-03-16 15:27
Hi @gilreathjw, thank you for opening this issue but since we're unable to reproduce the problem I'm going to close this. If you observe this behavior again, please reopen this issue and provide the steps so we can reproduce the problem and investigate.

**Closed by bsardo** 2023-03-16 15:27 UTC
